version: "3"

services:
  client:
    image: <accountid>.dkr.ecr.<region>.amazonaws.com/partner-meanstack-atlas-fargate-client
    platform: linux/amd64
    build: ./client
    ports:
      - 8080
  server:
    build: ./server
    image: <accountid>.dkr.ecr.<region>.amazonaws.com/partner-meanstack-atlas-fargate-server
    platform: linux/amd64
    ports:
      - 5200
